### ISSUE TITLE
can i make a pr with better material design?

### ISSUE THREAD

**Issue by ondraczsk** [pmt-mcpe-fun/UserInterface#3]
AITT All in the title
thanks

**Comment by Ad5001** [comment]
A PR is always welcome :)

**Comment by ondraczsk** [comment]
ok but if this pr takes a lot of time, so i hope you pull it (sry for my english)

**Comment by NFGamerMC** [comment]
You can, it most likely won’t be accepted as currently we are meeting the Google MDL guidelines. We do not need a re-design but you can add better animations if you want.

**Comment by ondraczsk** [comment]
but animations... i must make a new css and js so it must be re-coded

**Comment by NFGamerMC** [comment]
I will not accept that. We accept fixes and enchantments. We do not accept a re-design.

**Comment by NFGamerMC** [comment]
I am not telling you this because of your creepy and broken master.

**Comment by NFGamerMC** [comment]
BAJAN!
