### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ondraczsk** [pmt-mcpe-fun/UserInterface#4]
I want phar2zip

Warning: ZipArchive::close(): Can't open file: Permission denied in /var/www/pmt.mcpe.fun/pages/phar2zip/convert.php on line 82

Warning: chmod(): No such file or directory in /var/www/pmt.mcpe.fun/pages/phar2zip/convert.php on line 83

**Comment by Ad5001** [comment]
Should be fixed in a few seconds.

**Comment by ondraczsk** [comment]
ok
